GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyYTY3NDM3ZjY5NGFiYjMzMWJjNmNjMiIsImlhdCI6MTY1NTA3NzI5MX0.IuRhCmMGmBWJ8AIXGI3Y9Q2sWQToNmfHneRKYuOZob4
content-type: application/json

{
    "content": "foo ba 2r"
}