###
GET http://localhost:3001/api/blogs


###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "author",
  "url": 123
}

###
DELETE  http://localhost:3001/api/blogs/62a67ea6d358cb43c405a6df
